# Form implementation generated from reading ui file '.\Game.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 566)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.exit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout_3.addWidget(self.exit_btn, 6, 0, 1, 1)
        self.chat_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.chat_text.setReadOnly(True)
        self.chat_text.setObjectName("chat_text")
        self.gridLayout_3.addWidget(self.chat_text, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chat_enter_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.chat_enter_line.setObjectName("chat_enter_line")
        self.horizontalLayout.addWidget(self.chat_enter_line)
        self.chat_send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chat_send.setObjectName("chat_send")
        self.horizontalLayout.addWidget(self.chat_send)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.grid_btn_Layout = QtWidgets.QGridLayout()
        self.grid_btn_Layout.setObjectName("grid_btn_Layout")
        self.gridLayout_2.addLayout(self.grid_btn_Layout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_btn.setText(_translate("MainWindow", "Exit room"))
        self.chat_send.setText(_translate("MainWindow", "Send"))
        self.label.setText(_translate("MainWindow", "Timer: "))
