# Form implementation generated from reading ui file '.\registrationUI.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 192)
        MainWindow.setMinimumSize(QtCore.QSize(300, 192))
        MainWindow.setMaximumSize(QtCore.QSize(300, 192))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.registration_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.registration_text.setReadOnly(True)
        self.registration_text.setObjectName("registration_text")
        self.gridLayout.addWidget(self.registration_text, 0, 0, 1, 1)
        self.registration_enter_line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.registration_enter_line.setObjectName("registration_enter_line")
        self.gridLayout.addWidget(self.registration_enter_line, 1, 0, 1, 1)
        self.registration_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.registration_btn.setObjectName("registration_btn")
        self.gridLayout.addWidget(self.registration_btn, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registration_btn.setText(_translate("MainWindow", "Register"))
